### ISSUE TITLE
cfg/tags_36h11.yaml 

### ISSUE THREAD

**Issue by MJensen1231992** [christianrauch/apriltag_ros#13]
Hey Christian, 

It seems that the tag YAML was updated in the readme file, to mirror the change from bool to int in the latest change,
however the actual tags_36h11.yaml still contains the boolean version of refine and debug for the detector. 
Thank you.

**Comment by christianrauch** [comment]
I actually did not update the README file. I updated the configuration file in dc3d53571a32ff215bb7b61ae96e8bb9c9838104 just now.
