### ISSUE TITLE
Little doubt about the topic name "detections" is different from the name in AprilRobotics/apriltag_ros

### ISSUE THREAD

**Issue by s-c-c** [christianrauch/apriltag_ros#19]
First of all, thank you for  the ROS2 port. However, when I migrated from ros1 to ros2, I found that the topic name changed. In addition, compared to AprilRobotics/apriltag_ros, "tag_detections_image" is missing. Is there any reason for this?

**Comment by christianrauch** [comment]
This node only does the detection and pose estimation. It does not visualise the results. For visualisation, you can use https://github.com/christianrauch/apriltag_viz. What else are you missing?
