### ISSUE TITLE
publish debug image?

### ISSUE THREAD

**Issue by berndpfrommer** [christianrauch/apriltag_ros#25]
Hi!
Nice work with the apriltag detector node for ROS2!
I'd love to ditch my duplication-of-effort [here](https://github.com/berndpfrommer/apriltag_detector) in favor of your node, in particular since yours is already in rosdistro.
The one feature I'm missing though is a debug image. I find that very helpful so I was wondering if you were open to a PR that implements something like the picture below? The drawing is fairly lightweight and happens only when there is a subscription to the debug image. 

![image](https://github.com/christianrauch/apriltag_ros/assets/6206826/79494cc4-2c38-4bc1-bf41-821a540ba164)

**Comment by christianrauch** [comment]
When I created the tag detection node, I decided to move the optional visualisation into a separate node to keep the detection node minimal.

The visualisation node can be found here: https://github.com/christianrauch/apriltag_viz. It's a composable node that can be loaded into the same node manager. It essentially subscribes to the image and the tag detections and then publishes an image with the tags as overlay.

**Comment by berndpfrommer** [comment]
Ok, thanks for clarifying!
Will you release that node as a package as well?

**Comment by christianrauch** [comment]
I did not plan to release the visualiser to bloom.

**Comment by berndpfrommer** [comment]
ok
