### ISSUE TITLE
run detector without calibration?

### ISSUE THREAD

**Issue by berndpfrommer** [christianrauch/apriltag_ros#26]
I was planning on using the detector for calibration purposes, meaning there is no calibration available yet. I would only be using the corner positions and ID from the detection messages.
Any suggestions how to do this? The only way I see is to add another configuration parameter that would trigger the use of a regular image transport subscription rather than a camera subscription.

**Comment by christianrauch** [comment]
You can remap the topic to a topic with uncalibrated images (`image_raw`). You will still need to publish some fake `CameraInfo` messages (e.g. a default constructed message) on `camea_info` to trigger the synchronisation.

**Comment by berndpfrommer** [comment]
ok, thanks for clarifying!
