### ISSUE TITLE
Orientation difference between pnp and homography

### ISSUE THREAD

**Issue by eliasdc** [christianrauch/apriltag_ros#37]
The pose estimations have a different resulting frame.

- homography: z points inwards into the tag
- pnp: z points out of the tag

Ideally add a parameter to request which is preferred (in or out) than people can adopt between each. or include a rotation parameter.

**Comment by christianrauch** [comment]
I can reproduce this and am surprised that this wasn't caught in the discussions in https://github.com/christianrauch/apriltag_ros/issues/14. The z-axis of the tag frame is supposed to point away from the tag towards the camera (a.k.a. "outwards") as it is with the `pnp` option, which has been adapted from the ROS 1 node. See the second half of https://github.com/christianrauch/apriltag_ros/issues/14#issuecomment-1883943870 for an explanation of the tag frame orientation.

The `homography` option should produce the same tag frame orientation. IMHO, adding another option for the preferred tag orientation is not so useful as users can always apply additional transformations on top to achieve their desired tag orientation.

**Comment by christianrauch** [comment]
Does https://github.com/christianrauch/apriltag_ros/pull/38 fix your issue?
