### ISSUE TITLE
License

### ISSUE THREAD

**Issue by felipecode** [christianrauch/apriltag_ros#5]
Hello,
Thanks for this amazing port of apriltag to ros2.
I am just worried by one issue: this repo has no disclosed license.
I just want to be sure what is the author idea
 before I start using it more extensively on my projects.

**Comment by felipecode** [comment]
I found on the package.xml that the license is MIT

**Comment by christianrauch** [comment]
Good point, I wasn't so sure about the licence I chose either :-)

I added an MIT LICENSE file to the repo to make this more clear. In any case, this node is just a wrapper around the `apriltag` library which has the "BSD 2-Clause" licence. Both licences have the same conditions and grant you the same rights.
